name: Terraform 

on:
  workflow_dispatch:
#     inputs:
#       user_validation:
#         description: 'Validate the terraform code'
#         required: true
#         type: boolean

  push:
    branches: 
        - master

jobs:
  Azure:
    name: Install Azure CLI + terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # - name: Install Helm
      #   uses: azure/setup-helm@v1
      #   with:
      #     version: v3.2.4
          
      # - name: Helm version
      #   run: helm version
      
      # - name: Link to kubeconfig
      #   run: export KUBECONFIG=.kube/config

      # - name: Install nginx ingress controller
      #   run: |
      #     helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
      #     helm repo update
      #     helm install nginx-ingress ingress-nginx/ingress-nginx

      # - name: Link to kubeconfig
      #   run: export KUBECONFIG=.kube/config

      # - name: Install redis
      #   run: |
      #     helm repo add bitnami https://charts.bitnami.com/bitnami
      #     helm repo update
      #     helm install redis bitnami/redis

      - name: Install dependencies
        env: 
          TENANT_ID: ${{ secrets.TENANT_ID }}
          AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
          AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
        run: python -m pip install --upgrade pip && pip install azure-cli
      # Selon moi, cette partie ne marche pas avec mes identifiants car il y a des caractères spéciaux dans le mot de passe, ce qui doit perturber la commande (malheureusement je ne peux pas le modifier car c'est un compte fourni par l'école)
      - name: Login via Azure CLI
        run: az login -u "$AZURE_USERNAME" -p "$AZURE_PASSWORD" > /dev/null
          
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
      
      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate
      
      - name: Terraform Plan
        id: plan
        run: terraform plan

      - name: Manual approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ secrets.USERNAME_GITHUB }}
          minimum-approvals: 1
          issue-title: "Approval needed to go further"
          issue-body: "Please approve or deny the terraform apply"
          exclude-workflow-initiator-as-approver: false

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
    