name: Terraform 

on:
  workflow_dispatch:
    inputs:
      user_validation:
        description: 'Validate the terraform code'
        required: true
        type: boolean

  push:
    branches: 
        - master

jobs:
  Terraform:
    name: Terraform init+validate+plan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Terraform init
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.0
        tf_actions_subcommand: init
        tf_actions_working_dir: ../../

    - name: Terraform validate 
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.0
        tf_actions_subcommand: validate
        tf_actions_working_dir: ../../
        
    - name: Terraform plan 
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.0
        tf_actions_subcommand: plan
        tf_actions_working_dir: ../../